// app/layout.tsx
import type { Metadata } from "next";
import "@/app/globals.css";
import "@mantine/core/styles.css";
import { MantineProvider } from "@mantine/core";
import { redirect } from "next/navigation";
import { getSessionData } from "@/lib/session";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getSessionData();

  if (session.action === "logout") {
    return redirect("/logout");
  }
  return (
    <html lang="en">
      <body className="antialiased text-white">
        <MantineProvider>{children}</MantineProvider>
      </body>
    </html>
  );
}
